name: Deploy Preview
description: Deploys a preview environment using Vercel

inputs:
  vercel-token:
    description: 'Vercel authentication token'
    required: true
  turbo-token:
    description: 'Turborepo authentication token'
    required: true

outputs:
  preview-url:
    description: 'The preview URL of the deployment'
    value: ${{ steps.deploy.outputs.preview-url }}

runs:
  using: "composite"
  steps:
    - name: Build Project
      shell: bash
      run: |
        # Build with Turborepo for caching
        yarn turbo build --filter=@repo/web
        # Create Vercel output structure
        mkdir -p .vercel/output
        # Copy build output and create necessary metadata
        cp -r apps/web/.next .vercel/output/build
        echo '{"version": 2,"buildCommand": "yarn turbo build --filter=@repo/web","outputDirectory": "apps/web/.next"}' > .vercel/output/config.json
      env:
        TURBO_TOKEN: ${{ inputs.turbo-token }}

    - name: Deploy to Vercel
      id: deploy
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ inputs.vercel-token }}
        vercel-args: '--prebuilt'
      env:
        TURBO_TOKEN: ${{ inputs.turbo-token }} 