# This workflow runs on pull requests to main branch
# It builds, tests, and deploys a preview environment using Vercel
# Key features:
# - Prevents parallel deployments with concurrency
# - Uses MySQL and Redis for testing
# - Deploys frontend to Vercel preview
# - Runs backend locally for testing
# - Uses Turborepo for efficient builds and caching

name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

# Prevent parallel deployments
# - Groups deployments by workflow and PR
# - Cancels outdated deployments when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Global environment variables
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NODE_VERSION: '20'
  PORT: '3000'
  # MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  # MYSQL_DATABASE: test
  # REDIS_URL: redis://localhost:6379
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.WEB_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent jobs from hanging indefinitely
    
    # Service containers for MySQL and Redis
    # These are used by the backend service during testing
    # services:
    #   mysql:
    #     image: mysql:8.0
    #     env:
    #       MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
    #       MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
    #     ports:
    #       - 3306:3306
    #     options: >-
    #       --health-cmd="mysqladmin ping"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3

    #   redis:
    #     image: redis:7.0
    #     ports:
    #       - 6379:6379
    #     options: >-
    #       --health-cmd="redis-cli ping"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3

    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Shallow clone for faster checkout

      # Setup Node and install dependencies
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      # Cache Turborepo outputs for faster builds
      - name: Setup Turborepo
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turbo-
        
      # Deploy frontend to Vercel preview environment
      - uses: ./.github/actions/deploy-preview
        id: deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          turbo-token: ${{ env.TURBO_TOKEN }}
          vercel-project-id: ${{ env.WEB_PROJECT_ID }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
        
      # Start backend service for testing
      # - name: Start Backend Service
      #   run: yarn turbo dev --filter=api & npx wait-on http://localhost:8000
      #   env:
      #     DATABASE_URL: mysql://root:${{ env.MYSQL_ROOT_PASSWORD }}@localhost:3306/${{ env.MYSQL_DATABASE }}
      #     REDIS_URL: ${{ env.REDIS_URL }}
        
      # Run linting and tests against the deployed frontend
      - name: Run Tests
        run: |
          yarn turbo lint --filter=@repo/web
          yarn turbo test --filter=@repo/web
        env:
          CYPRESS_BASE_URL: ${{ steps.deploy.outputs.preview-url }}
          TURBO_TOKEN: ${{ env.TURBO_TOKEN }}
